name: pytest-macos

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: macos-14
    
    steps:
    - name: Checkout PyHelios
      uses: actions/checkout@v4
      with:
        submodules: recursive
        
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install XQuartz
      run: |
        brew install --cask xquartz
        
    - name: Install build dependencies only
      run: |
        python -m pip install --upgrade pip
        
    - name: Build native libraries
      run: |
        python build_scripts/build_helios.py --buildmode release --nogpu --verbose
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: macos-build-artifacts
        path: |
          pyhelios_build/build/
          pyhelios/plugins/*.so
          pyhelios/plugins/*.dylib
        retention-days: 1

  test:
    needs: build
    runs-on: macos-14
    
    steps:
    - name: Checkout PyHelios
      uses: actions/checkout@v4
      with:
        submodules: recursive
        
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: macos-build-artifacts
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev]
        
    - name: Run pytest
      run: |
        pytest -v